// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDchTa7a0HiE-ezluwk00s-SSrwE593cCc',
    appId: '1:1088453123089:web:a8a1ff09e4314a5252e5b0',
    messagingSenderId: '1088453123089',
    projectId: 'ez-vocab-c96be',
    authDomain: 'ez-vocab-c96be.firebaseapp.com',
    storageBucket: 'ez-vocab-c96be.firebasestorage.app',
    measurementId: 'G-W9LCQS9SQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjHlYDafpG22sKJFOpnf29ju1G-KR4PFA',
    appId: '1:1088453123089:android:910ef04b03b98cf552e5b0',
    messagingSenderId: '1088453123089',
    projectId: 'ez-vocab-c96be',
    storageBucket: 'ez-vocab-c96be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX6cUFHmhNMnQ34P5pxM1HUrkEG6xX7ZE',
    appId: '1:1088453123089:ios:c031460cc77649f952e5b0',
    messagingSenderId: '1088453123089',
    projectId: 'ez-vocab-c96be',
    storageBucket: 'ez-vocab-c96be.firebasestorage.app',
    iosBundleId: 'com.example.ezVocab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX6cUFHmhNMnQ34P5pxM1HUrkEG6xX7ZE',
    appId: '1:1088453123089:ios:c031460cc77649f952e5b0',
    messagingSenderId: '1088453123089',
    projectId: 'ez-vocab-c96be',
    storageBucket: 'ez-vocab-c96be.firebasestorage.app',
    iosBundleId: 'com.example.ezVocab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDchTa7a0HiE-ezluwk00s-SSrwE593cCc',
    appId: '1:1088453123089:web:59685dbd1dd58c9a52e5b0',
    messagingSenderId: '1088453123089',
    projectId: 'ez-vocab-c96be',
    authDomain: 'ez-vocab-c96be.firebaseapp.com',
    storageBucket: 'ez-vocab-c96be.firebasestorage.app',
    measurementId: 'G-8RNERXQYF2',
  );

}